name: "Android CI + CD (Calling Repo)"

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]
    tags:
      - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # CI for PRs and branch pushes
  ci:
    uses: Darryl-Cardoza/reusable-repo-android/.github/workflows/push.yml@main
    with:
      java_version: "17"
      build_variant: "Debug"
      coverage_threshold: "40.00"

  # CD for version tags
  cd:
    uses: Darryl-Cardoza/reusable-repo-android/.github/workflows/release.yml@main
    with:
      version: ${{ github.ref_name }} # already like v1.2.3 (if you want without v, see note below)
      java_version: "17"
      build_variant: "Release"
      coverage_threshold: "40.00"

      deploy_to_playstore: true
      package_name: "com.devops.test"
      playstore_track: "internal"
      playstore_status: "completed"

      deploy_to_esper: false

    secrets:
      ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      PLAYSTORE_SERVICE_ACCOUNT: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}

